version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
                  
      - name: sales
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: id of the orders
          - name: pdt_id
            description: id of the products
          - name: revenue
            description: quantity multiplied by price
          - name: quantity
            description: number of products
        tests:
            - unique:
                column_name: "(orders_id || '' || pdt_id )"
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: Advertising data from Google Adwords

      - name: bing    
        identifier: raw_gz_bing
        description: Advertising data from Bing Ads

      - name: criteo    
        identifier: raw_gz_criteo
        description: Advertising data from Criteo                 
                  
      - name: facebook    
        identifier: raw_gz_facebook
        description: Advertising data from Facebook Ads    

models:
  - name: int_campaigns
    description: Aggregated campaign costs from different advertising platforms
    tests:
      - unique:
          column_name: "(campaign_key||'_'||date_date)"
    columns:
      - name: date_date
        description: "Date of the campaign data"
        tests:
          - not_null

      - name: paid_source
        description: "Source of the paid advertisement"
        tests:
          - not_null
          - accepted_values:
              values: ['Adwords', 'Bing', 'Facebook', 'Criteo']

      - name: campaign_key
        description: "Unique key for each campaign"
        tests:
          - not_null
          
      - name: campaign_name
        description: "Name of the campaign"
        tests:
          - not_null

      - name: ads_cost
        description: "Cost of the advertisements"
        tests:
          - not_null

      - name: impression
        description: "Number of times the ad was shown"
        tests:
          - not_null

      - name: click
        description: "Number of clicks the ad received"
        tests:
          - not_null
      

        
          
        
      